/**
 * Default Seed Data for Database Initialization
 */

const defaultCategories = [
  {
    id: "plastic-lumber",
    name: "Plastic Lumber",
    slug: "plastic-lumber",
    description: "Timber alternatives engineered for high strength and structural durability.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    fields: JSON.stringify([
      { name: "Size", label: "Profile Size", type: "text", placeholder: "e.g. 2x4 in, 4x4 in" },
      { name: "Color", label: "Color Options", type: "text", placeholder: "e.g. Teak, Grey, Black" },
      { name: "Length", label: "Standard Length", type: "text", placeholder: "e.g. 8 ft, 12 ft" },
    ]),
  },
  {
    id: "plastic-pallets",
    name: "Plastic Pallets",
    slug: "plastic-pallets",
    description: "ISPM-15 compliant heavy-duty pallets built for global export shipping.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    fields: JSON.stringify([
      { name: "Dimensions", label: "Dimensions (L x W x H)", type: "text", placeholder: "e.g. 1200 x 1000 x 150 mm" },
      { name: "Static Load", label: "Static Load Capacity", type: "text", placeholder: "e.g. 5000 kg" },
      { name: "Dynamic Load", label: "Dynamic Load Capacity", type: "text", placeholder: "e.g. 1500 kg" },
    ]),
  },
  {
    id: "garden-bench",
    name: "Garden Bench",
    slug: "garden-bench",
    description: "Elegant and weather-resistant recycled plastic benches for municipal parks.",
    image: "/uploads/products/categories/garden-bench-1770446422580-0_medium.webp",
    fields: JSON.stringify([
      { name: "Seating Capacity", label: "Seating Capacity", type: "text", placeholder: "e.g. 3-4 Persons" },
      { name: "Frame Material", label: "Frame / Support Material", type: "text", placeholder: "e.g. Heavy Duty Recycled HDPE / Cast Iron" },
    ]),
  },
  {
    id: "plastic-table",
    name: "Plastic Table",
    slug: "plastic-table",
    description: "Circular outdoor dining tables designed to withstand harsh outdoor weather.",
    image: "",
    fields: JSON.stringify([]),
  },
  {
    id: "garden-fence",
    name: "Garden Fence",
    slug: "garden-fence",
    description: "Maintenance-free perimeter fencing systems designed for residential use.",
    image: "",
    fields: JSON.stringify([]),
  },
  {
    id: "outdoor-furniture",
    name: "Outdoor Furniture",
    slug: "outdoor-furniture",
    description: "Sleek, sustainable, and durable furniture built for modern spaces.",
    image: "",
    fields: JSON.stringify([]),
  },
  {
    id: "custom-products",
    name: "Custom Products",
    slug: "custom-products",
    description: "Bespoke industrial shapes and parts molded to custom B2B drawings.",
    image: "",
    fields: JSON.stringify([]),
  },
];

const defaultProducts = [
  {
    id: "rpl-2x4-standard",
    name: "Structural Recycled Plastic Lumber 2x4",
    category: "plastic-lumber",
    type: "Standard Profile",
    description: "High-density recycled polyethylene (HDPE) lumber designed to replace structural timber. Rot-proof, termite-proof, and maintenance-free for over 50 years.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Inquire for B2B Pricing",
    moq: "50 Pieces",
    capacity: "Heavy Duty Construction Grade",
    dispatch: "3-5 Business Days",
    customization: "Custom lengths & color matching available",
    technical_blurb: "100% recycled HDPE polyolefins with UV-8 stabilizers. Zero absorption rate ensures immunity against mold, rot, and splintering.",
    applications: "Decks, Marinas, Retaining Walls, Agricultural Fencing, Industrial Flooring",
    specifications: JSON.stringify({ Size: "2x4 inches (38x89mm)", Color: "Teak / Charcoal / Black", Length: "8ft / 10ft / 12ft", Material: "100% Recycled HDPE" }),
    features: JSON.stringify(["50+ Year Outdoor Lifespan", "Zero Water Absorption & No Splinters", "UV Stabilized against Fading", "100% Recyclable at End-of-Life"]),
    published: 1,
  },
  {
    id: "hd-export-pallet-1210",
    name: "Heavy-Duty Rackable Plastic Pallet 1200x1000",
    category: "plastic-pallets",
    type: "Industrial Export Pallet",
    description: "ISPM-15 exempt heavy-duty industrial pallet for high-bay warehousing, rack loading, and automated logistics networks.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    price: "Inquire for Volume Quote",
    moq: "100 Units",
    capacity: "Static 5,000kg / Dynamic 1,500kg / Racking 1,000kg",
    dispatch: "Immediate Dispatch Available",
    customization: "Brand logo embossing & RFID tracking slots",
    technical_blurb: "Monobloc molded polypropylene/HDPE composite. Hygienic non-porous structure resistant to acids, alkalis, and moisture.",
    applications: "Warehouse Racking, Chemical Logistics, Food & Beverage Export, Cold Storage",
    specifications: JSON.stringify({ Dimensions: "1200 x 1000 x 150 mm", "Static Load": "5,000 kg", "Dynamic Load": "1,500 kg", "Racking Load": "1,000 kg" }),
    features: JSON.stringify(["ISPM-15 Exempt (No Fumigation Required)", "4-Way Forklift & Pallet Jack Entry", "Anti-Slip Rubber Grommets", "100% Weather & Chemical Resistant"]),
    published: 1,
  },
  {
    id: "municipal-eco-bench-180",
    name: "Eco Park & Municipal Bench 1.8m",
    category: "garden-bench",
    type: "Outdoor Furniture",
    description: "Heavy-duty outdoor bench manufactured from recycled plastic planks on a reinforced steel substructure. Ideal for public parks, school campuses, and corporate gardens.",
    image: "/uploads/products/garden-bench/gardenbench-1770441701366-1_medium.webp",
    price: "Inquire for Municipal Quote",
    moq: "10 Benches",
    capacity: "4 Adult Seating Capacity (450 kg)",
    dispatch: "5-7 Business Days",
    customization: "Plank color options & memorial plaque engraving",
    technical_blurb: "UV-protected recycled plastic planks mounted on powder-coated steel frame with anti-theft ground anchoring system.",
    applications: "Public Parks, University Campuses, Municipal Sidewalks, Waterfront Promenades",
    specifications: JSON.stringify({ Length: "1800 mm", "Seating Capacity": "4 Persons", Weight: "48 kg", Color: "Forest Green / Brown" }),
    features: JSON.stringify(["Vandalism & Graffiti Resistant", "Zero Painting or Staining Required", "Ground Anchoring System Included", "Eco-friendly Carbon Credit Offset"]),
    published: 1,
  },
];

const defaultCompany = {
  logo: "/uploads/products/company/company-1770632843872-58035_medium.webp",
  name: "VISHAL ENTERPRISE",
  tagline: "Circular Polymers & Recycled Solutions",
  description: "Transforming industrial plastic waste into premium recycled lumber, pallets, and custom outdoor structures since 2008. ISO 9001:2015 Certified.",
  established: "2008",
  phone: "+91 98986 86379",
  whatsapp: "919898686379",
  email: "info@vishalenterprise.com",
  address: "Plot No. 42, GIDC Industrial Estate",
  city: "Vapi",
  state: "Gujarat",
  pincode: "396191",
};

module.exports = {
  defaultCategories,
  defaultProducts,
  defaultCompany,
};
