import {
  MotionHardHat,
  MotionShieldCheck,
  MotionRoute,
  MotionTrees,
  MotionSchool,
  MotionWarehouse,
  MotionSprout,
  MotionHomeIcon,
  MotionBuilding2,
  hardHatVariants,
  shieldCheckVariants,
  routeVariants,
  treesVariants,
  schoolVariants,
  warehouseVariants,
  sproutVariants,
  homeIconVariants,
  building2Variants,
} from "./home.constants";

export const INDUSTRIES_DATA = [
  {
    id: "construction",
    title: "Construction & Civil",
    desc: "Heavy-duty structural formwork, framing lumber, shoring blocks, and site protection barriers built to withstand extreme mechanical loads and jobsite wear.",
    image: "https://images.unsplash.com/photo-1541888081254-20a2e374ff19?q=80&w=1200&auto=format&fit=crop",
    delay: 0,
    cardType: "featured",
    badgeText: "Core Sector",
    badgeClass: "bentoBadgeLime",
    IconComponent: MotionHardHat,
    iconVariants: hardHatVariants,
    iconBoxClass: "iconBoxLime",
    statIcon: MotionShieldCheck,
    statVariants: shieldCheckVariants,
    statText: "50+ Year Lifespan",
    tagText: "Zero Rot",
  },
  {
    id: "infrastructure",
    title: "Infrastructure",
    desc: "Civic walkways, bridge decking, railway sleepers, and sound abatement panels.",
    image: "https://images.unsplash.com/photo-1513828583688-c52646db42da?q=80&w=1000&auto=format&fit=crop",
    delay: 0.05,
    cardType: "standard",
    IconComponent: MotionRoute,
    iconVariants: routeVariants,
    iconBoxClass: "iconBoxSlate",
  },
  {
    id: "municipal",
    title: "Municipal Parks",
    desc: "Weatherproof park benches, picnic tables, trash receptacles, and bollards.",
    image: "https://images.unsplash.com/photo-1519974719765-e6559eac2575?q=80&w=1000&auto=format&fit=crop",
    delay: 0.1,
    cardType: "standard",
    IconComponent: MotionTrees,
    iconVariants: treesVariants,
    iconBoxClass: "iconBoxSlate",
  },
  {
    id: "education",
    title: "Education",
    desc: "Durable outdoor campus seating, play equipment framing, and perimeter fencing.",
    image: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?q=80&w=1000&auto=format&fit=crop",
    delay: 0.15,
    cardType: "wide",
    spanClass: "span2",
    IconComponent: MotionSchool,
    iconVariants: schoolVariants,
    iconBoxClass: "iconBoxSlate",
  },
  {
    id: "warehousing",
    title: "Warehousing & Cold Logistics",
    desc: "High-density rackable pallets, skid boards, and cold storage platforms engineered for automated high-bay warehouses and multi-ton forklift operations.",
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=1000&auto=format&fit=crop",
    delay: 0.2,
    cardType: "wideHeader",
    spanClass: "span2",
    badgeText: "Heavy Industrial",
    badgeClass: "bentoBadgeBlue",
    IconComponent: MotionWarehouse,
    iconVariants: warehouseVariants,
    iconBoxClass: "iconBoxNavy",
  },
  {
    id: "agriculture",
    title: "Agriculture",
    desc: "Rot-proof greenhouse benching, raised garden beds, and livestock fencing.",
    image: "https://images.unsplash.com/photo-1530018607912-eff2daa1bac4?q=80&w=1000&auto=format&fit=crop",
    delay: 0.25,
    cardType: "wide",
    spanClass: "span2",
    IconComponent: MotionSprout,
    iconVariants: sproutVariants,
    iconBoxClass: "iconBoxGreen",
  },
  {
    id: "residential",
    title: "Residential",
    desc: "Low-maintenance deck substructures, garden fences, and outdoor patio furniture.",
    image: "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=1200&auto=format&fit=crop",
    delay: 0.3,
    cardType: "wideRow",
    spanClass: "span4",
    IconComponent: MotionHomeIcon,
    iconVariants: homeIconVariants,
    iconBoxClass: "iconBoxLime",
  },
  {
    id: "commercial",
    title: "Commercial & Hospitality",
    desc: "Resort outdoor loungers, corporate campus amenities, and custom architectural fixtures tailored for zero-maintenance public spaces.",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
    delay: 0.35,
    cardType: "wideRowHeader",
    spanClass: "span4",
    isDark: true,
    badgeText: "Commercial Grade",
    badgeClass: "bentoBadgeLimeDark",
    IconComponent: MotionBuilding2,
    iconVariants: building2Variants,
    iconBoxClass: "iconBoxLime",
  },
];
