/**
 * Comprehensive Product & Category Catalog Seeder
 * Seeds plastic pallets (multiple sizes/types), plastic lumber, garden benches,
 * and tables made from recycled plastic lumber.
 */
const path = require("path");
const fs = require("fs");
const { createClient } = require("@libsql/client");

const dbPath =
  process.env.DB_PATH ||
  (fs.existsSync("/app/data/vishal_enterprise.db")
    ? "/app/data/vishal_enterprise.db"
    : path.join(__dirname, "../../../../../data/vishal_enterprise.db"));

console.log("Connecting to database at:", dbPath);
const client = createClient({ url: `file:${dbPath}` });

const categories = [
  {
    id: "plastic-pallets",
    name: "Plastic Pallets",
    slug: "plastic-pallets",
    description: "ISPM-15 exempt heavy-duty, racking, euro, and export plastic pallets in standard and custom sizes.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    fields: JSON.stringify([
      { name: "Dimensions", label: "Dimensions (L x W x H)", type: "text", placeholder: "e.g. 1200 x 1000 x 150 mm" },
      { name: "Static Load", label: "Static Load Capacity", type: "text", placeholder: "e.g. 5000 kg" },
      { name: "Dynamic Load", label: "Dynamic Load Capacity", type: "text", placeholder: "e.g. 1500 kg" },
      { name: "Racking Load", label: "Racking Load Capacity", type: "text", placeholder: "e.g. 1000 kg" },
      { name: "Entry Type", label: "Forklift Entry", type: "text", placeholder: "e.g. 4-Way / 2-Way" },
    ]),
  },
  {
    id: "plastic-lumber",
    name: "Plastic Lumber",
    slug: "plastic-lumber",
    description: "100% recycled HDPE structural lumber profiles, posts, planks, and battens replacing rot-prone wood.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    fields: JSON.stringify([
      { name: "Size", label: "Profile Size", type: "text", placeholder: "e.g. 2x4 in, 4x4 in" },
      { name: "Dimensions", label: "Metric Dimensions", type: "text", placeholder: "e.g. 38 x 89 mm" },
      { name: "Standard Length", label: "Standard Length", type: "text", placeholder: "e.g. 8 ft, 10 ft, 12 ft" },
      { name: "Color", label: "Available Colors", type: "text", placeholder: "e.g. Teak, Charcoal, Walnut" },
    ]),
  },
  {
    id: "garden-bench",
    name: "Garden Benches",
    slug: "garden-bench",
    description: "Heavy-duty municipal, park, and society garden benches made from weatherproof recycled plastic lumber.",
    image: "/uploads/products/garden-bench/gardenbench-1770441701366-1_medium.webp",
    fields: JSON.stringify([
      { name: "Length", label: "Bench Length", type: "text", placeholder: "e.g. 1500 mm / 1800 mm" },
      { name: "Seating Capacity", label: "Seating Capacity", type: "text", placeholder: "e.g. 3-4 Persons" },
      { name: "Frame Material", label: "Support / Frame", type: "text", placeholder: "e.g. Recycled HDPE / Cast Iron" },
      { name: "Anchoring", label: "Mounting Type", type: "text", placeholder: "e.g. Surface / Ground Bolt" },
    ]),
  },
  {
    id: "plastic-table",
    name: "Recycled Plastic Tables",
    slug: "plastic-table",
    description: "Commercial and recreational outdoor tables and picnic ensembles made from 100% recycled plastic lumber.",
    image: "/uploads/products/categories/plastic-table-1770446441648-0_medium.webp",
    fields: JSON.stringify([
      { name: "Dimensions", label: "Table Dimensions", type: "text", placeholder: "e.g. 1800 x 1500 x 750 mm" },
      { name: "Seating Capacity", label: "Seating Capacity", type: "text", placeholder: "e.g. 4-8 Persons" },
      { name: "Tabletop Style", label: "Tabletop Pattern", type: "text", placeholder: "e.g. Plastic Lumber Planks" },
    ]),
  },
  {
    id: "custom-products",
    name: "Custom Products & Fencing",
    slug: "custom-products",
    description: "Bespoke industrial profiles, tree-guards, ranch boundary fencing, and fabricated lumber solutions.",
    image: "/uploads/products/categories/categories-1770374476904-61107_medium.webp",
    fields: JSON.stringify([
      { name: "Application", label: "Industrial Application", type: "text", placeholder: "e.g. Agricultural, Industrial" },
      { name: "Customization", label: "Custom Profile Options", type: "text", placeholder: "e.g. Custom extrusions" },
    ]),
  },
];

const products = [
  // ================= PALLETS =================
  {
    id: "pallet-hd-racking-1210",
    name: "Heavy-Duty Rackable Plastic Pallet 1200x1000",
    category: "plastic-pallets",
    type: "Racking Pallet",
    description: "Engineered for high-bay warehouse racking and automated AS/RS systems. Built with 3 steel-reinforced runners and anti-skid rubber grommets for maximum safety.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    price: "Inquire for B2B Pricing",
    moq: "50 Units",
    capacity: "Static 5,000kg / Dynamic 1,500kg / Racking 1,000kg",
    dispatch: "Ready Stock Dispatch",
    customization: "RFID tags, company logo hot-stamping, and color selection",
    technical_blurb: "Molded from ultra-high molecular HDPE with impact modifiers. Withstands severe cold room storage (-30°C to +60°C) without cracking.",
    applications: "High-Bay Warehouse Racking, Heavy Chemical Storage, Cold Storage, FMCG Distribution",
    specifications: JSON.stringify({
      Dimensions: "1200 x 1000 x 150 mm",
      "Static Load": "5,000 kg",
      "Dynamic Load": "1,500 kg",
      "Racking Load": "1,000 kg",
      "Forklift Entry": "4-Way Entry (Forklift & Pallet Jack)",
      Weight: "14.5 kg",
      Material: "100% Recycled HDPE Composite",
    }),
    features: JSON.stringify([
      "ISPM-15 Exempt (Zero Fumigation Needed for Global Export)",
      "3 Bottom Runners with Racking Reinforcement",
      "Anti-Slip Rubber Grommets on Deck and Bottom",
      "Washable & Chemical Resistant Surface",
    ]),
    published: 1,
  },
  {
    id: "pallet-euro-export-1208",
    name: "Euro Standard Export Pallet 1200x800",
    category: "plastic-pallets",
    type: "Euro Pallet",
    description: "Standard European footprint (1200 x 800 mm) lightweight export pallet. Perfectly optimized for air freight, ocean container stuffing, and cross-border logistics.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    price: "Inquire for Volume Pricing",
    moq: "100 Units",
    capacity: "Static 3,500kg / Dynamic 1,200kg / Racking 600kg",
    dispatch: "2-4 Business Days",
    customization: "Custom barcode embossing, corner anti-slip lips",
    technical_blurb: "Precision monobloc molded design providing zero moisture absorption, making it immune to mold, termites, and microbiological growth.",
    applications: "Pharmaceutical Export, Automotive Components, Electronics Air Freight, European Supply Chains",
    specifications: JSON.stringify({
      Dimensions: "1200 x 800 x 144 mm",
      "Static Load": "3,500 kg",
      "Dynamic Load": "1,200 kg",
      "Racking Load": "600 kg",
      "Forklift Entry": "4-Way Entry",
      Weight: "10.8 kg",
      Material: "Virgin / Recycled PP/HDPE Blend",
    }),
    features: JSON.stringify([
      "Conforms to Standard European EPAL Dimensions",
      "Nestable / Stackable design saves up to 55% return freight",
      "No nails or splinters to damage packed cartons",
      "100% Recyclable circular economy product",
    ]),
    published: 1,
  },
  {
    id: "pallet-2way-entry-1111",
    name: "Medium-Duty 2-Way Pallet 1100x1100",
    category: "plastic-pallets",
    type: "2-Way Pallet",
    description: "Square 1100 x 1100 mm footprint heavy plastic pallet designed for chemical drums, liquid IBC tanks, and shipping container optimization.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    price: "Inquire for B2B Pricing",
    moq: "50 Units",
    capacity: "Static 4,000kg / Dynamic 1,300kg",
    dispatch: "3-5 Business Days",
    customization: "Perimeter lip options (5mm or flat flush deck)",
    technical_blurb: "Continuous solid runner design enables smooth movement across roller conveyors and provides rigid stability for 210-liter oil drums.",
    applications: "Chemical Drum Storage, Paint & Resin Warehousing, Sea Container Loading, Fertilizer Bags",
    specifications: JSON.stringify({
      Dimensions: "1100 x 1100 x 140 mm",
      "Static Load": "4,000 kg",
      "Dynamic Load": "1,300 kg",
      "Forklift Entry": "2-Way Forklift Entry",
      Weight: "12.2 kg",
      Material: "High Density Polyethylene (HDPE)",
    }),
    features: JSON.stringify([
      "Optimized Square Footprint for 4 Standard Barrels",
      "Conveyor-Friendly Solid Runner Underside",
      "Acid & Alkali Resistant Inert Polymer",
      "High UV Stability for Outdoor Storage",
    ]),
    published: 1,
  },
  {
    id: "pallet-4way-reversible-1212",
    name: "Heavy-Duty Reversible Pallet 1200x1200",
    category: "plastic-pallets",
    type: "Reversible Pallet",
    description: "Double-deck reversible plastic pallet featuring identical top and bottom surfaces. Ideal for bulk bag stacking, flour/cement stacking, and heavy manufacturing.",
    image: "/uploads/products/pallets/pallets-1770374237161-67758_medium.webp",
    price: "Inquire for Volume Pricing",
    moq: "40 Units",
    capacity: "Static 6,000kg / Dynamic 2,000kg / Racking 1,200kg",
    dispatch: "5-7 Business Days",
    customization: "High-contrast colors & RFID asset tracking chips",
    technical_blurb: "Reversible double-sided deck distributes tier loads evenly, preventing crushing of bags or bottom packaging during multi-tier stacking.",
    applications: "Flour & Sugar Mills, Cement Bags, Petrochemical Granule Bags, Heavy Foundry Components",
    specifications: JSON.stringify({
      Dimensions: "1200 x 1200 x 160 mm",
      "Static Load": "6,000 kg",
      "Dynamic Load": "2,000 kg",
      "Racking Load": "1,200 kg",
      "Forklift Entry": "4-Way Entry (Forklift only)",
      Weight: "19.5 kg",
      Material: "Reinforced Recycled HDPE",
    }),
    features: JSON.stringify([
      "Dual Identical Decking for Safe Tier Stacking",
      "Highest Static Capacity (up to 6 Tonnes)",
      "High Torsional Rigidity under Forklift Acceleration",
      "Long Service Life Exceeding 10 Years",
    ]),
    published: 1,
  },
  {
    id: "pallet-plastic-lumber-skid",
    name: "Custom Recycled Plastic Lumber Skid 1300x1100",
    category: "plastic-pallets",
    type: "Plastic Lumber Skid",
    description: "Constructed entirely from solid structural recycled plastic lumber battens and runners. Engineered to support non-standard heavy equipment and machinery.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Custom Built to Specs",
    moq: "25 Units",
    capacity: "Static 7,000kg / Dynamic 2,500kg",
    dispatch: "Built to Order (5-7 Days)",
    customization: "Custom lengths up to 3 meters, plank spacing, and steel threaded inserts",
    technical_blurb: "Fabricated using 38x89mm recycled HDPE lumber fastened with 316 stainless steel countersunk hardware. Completely customizable to custom factory machinery footprints.",
    applications: "Transformer Transport, Heavy Machinery Skids, Coil Crates, Steel Pipe Bundles",
    specifications: JSON.stringify({
      Dimensions: "1300 x 1100 x 150 mm (Customizable)",
      "Static Load": "7,000 kg",
      "Dynamic Load": "2,500 kg",
      "Forklift Entry": "4-Way / 2-Way Hybrid",
      Weight: "26 kg",
      Material: "Solid Structural Recycled Plastic Lumber (HDPE)",
    }),
    features: JSON.stringify([
      "Zero Tooling/Mold Cost for Custom Dimensions",
      "Solid Lumber Planks Withstand Extreme Point Loads",
      "Will Never Rot or Degrade in Marine / Acidic Environments",
      "Repairable Modular Design",
    ]),
    published: 1,
  },

  // ================= LUMBER =================
  {
    id: "lumber-rpl-2x4",
    name: "Structural Recycled Plastic Lumber 2x4 (38x89mm)",
    category: "plastic-lumber",
    type: "Standard Lumber Profile",
    description: "Heavy-duty recycled HDPE lumber engineered as a direct replacement for 2x4 treated timber. Never rots, warps, or splinters, making it ideal for outdoor construction.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Inquire for Per-Meter / Bundle Rates",
    moq: "50 Pieces",
    capacity: "Structural Construction Grade",
    dispatch: "Immediate Stock in 8ft & 10ft",
    customization: "Custom cutoff lengths, teak/charcoal/black/walnut colors",
    technical_blurb: "100% post-consumer & post-industrial HDPE polymer stabilized with UV absorbers. Can be cut, drilled, routed, and screwed using standard woodworking tools.",
    applications: "Outdoor Decking Substructure, Marina Docks, Park Benches, Industrial Flooring, Retaining Walls",
    specifications: JSON.stringify({
      "Profile Size": "2x4 inches (38 x 89 mm)",
      "Standard Lengths": "8 ft (2.4m) / 10 ft (3.0m) / 12 ft (3.65m)",
      Density: "0.95 - 0.97 g/cm³",
      Material: "100% Recycled High-Density Polyethylene",
      Colors: "Teak Brown, Charcoal Grey, Jet Black, Forest Green",
    }),
    features: JSON.stringify([
      "50+ Year Expected Lifespan with Zero Maintenance",
      "Zero Water Absorption (< 0.1%) — Rot Proof & Termite Proof",
      "Works with Standard Carpentry Saws and Screws",
      "Paint-Free Color Formulated Solid Throughout",
    ]),
    published: 1,
  },
  {
    id: "lumber-rpl-4x4-post",
    name: "Heavy-Duty Structural RPL Post 4x4 (90x90mm)",
    category: "plastic-lumber",
    type: "Structural Post",
    description: "Solid, dense square profile post designed for heavy vertical load-bearing applications, signposts, pergola uprights, and dock pilings.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Inquire for Wholesale Rates",
    moq: "20 Pieces",
    capacity: "High Compressive Load Bearing",
    dispatch: "3-5 Business Days",
    customization: "Chamfered top caps, pre-drilled bolt holes",
    technical_blurb: "Extruded solid core without voids. Resistant to soil microorganisms, fertilizers, salt water, and petroleum spills.",
    applications: "Highway Guardrails, Pergola Posts, Marine Docks, Horse Paddock Fencing, Security Barriers",
    specifications: JSON.stringify({
      "Profile Size": "4x4 inches (90 x 90 mm)",
      "Standard Lengths": "8 ft (2.4m) / 10 ft (3.0m)",
      Weight: "7.8 kg/meter",
      Material: "Recycled Polyolefin / HDPE Composite",
      Colors: "Black, Walnut, Teak, Charcoal",
    }),
    features: JSON.stringify([
      "Can be directly buried in soil/concrete without rotting",
      "Impervious to sea water, salt spray, and barnacles",
      "No chemical leaching — safe for agriculture & livestock",
      "Graffiti-resistant easy-clean non-porous surface",
    ]),
    published: 1,
  },
  {
    id: "lumber-rpl-2x6-decking",
    name: "Recycled Plastic Lumber Decking Plank 2x6 (38x140mm)",
    category: "plastic-lumber",
    type: "Decking Plank",
    description: "Wide-format structural plank with embossed woodgrain or grooved anti-slip surface. Perfect for boardwalks, footbridges, terraces, and wet walkways.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Inquire for Project Quotes",
    moq: "40 Pieces",
    capacity: "Pedestrian & Light Utility Vehicle Traffic",
    dispatch: "3-5 Business Days",
    customization: "Smooth, embossed woodgrain, or ribbed anti-slip finish",
    technical_blurb: "Engineered with anti-slip micro-texture. Maintains high coefficient of friction even when fully submerged or wet.",
    applications: "Wetland Boardwalks, Coastal Walkways, Swimming Pool Decks, Public Pier Decking",
    specifications: JSON.stringify({
      "Profile Size": "2x6 inches (38 x 140 mm)",
      "Standard Lengths": "10 ft (3.0m) / 12 ft (3.65m)",
      Weight: "5.1 kg/meter",
      Material: "100% Recycled HDPE",
      Colors: "Weathered Grey, Teak Brown, Walnut, Charcoal",
    }),
    features: JSON.stringify([
      "Safe Barefoot Walking with Zero Splinters",
      "Anti-Slip Surface for High-Wetness Environments",
      "Does Not Warp, Cup, or Twist under Direct Sunlight",
      "Resistant to Chlorine, Saltwater, and Mild Acids",
    ]),
    published: 1,
  },
  {
    id: "lumber-rpl-tongue-groove",
    name: "Tongue & Groove Interlocking Lumber Plank (25x125mm)",
    category: "plastic-lumber",
    type: "Interlocking Plank",
    description: "Precision-milled tongue & groove profiles that interlock seamlessly to create solid, wind-tight, and water-shedding partition walls and gates.",
    image: "/uploads/products/lumber/plastic-lumber-pallet-1770447286569-0_medium.webp",
    price: "Inquire for B2B Pricing",
    moq: "60 Pieces",
    capacity: "Heavy Impact Resistance",
    dispatch: "3-5 Business Days",
    customization: "Double-sided woodgrain embossing, custom cut lengths",
    technical_blurb: "Interlocking joints accommodate thermal expansion while preserving tight wall integrity. Resists animal chewing and kicks.",
    applications: "Horse Stables, Compost Bins, Privacy Gates, Noise Barriers, Industrial Planters",
    specifications: JSON.stringify({
      "Profile Size": "1x5 inches (25 x 125 mm)",
      "Standard Lengths": "8 ft (2.44m)",
      Weight: "2.9 kg/meter",
      Material: "High Impact Recycled Polymer",
      Colors: "Equestrian Brown, Forest Green, Black",
    }),
    features: JSON.stringify([
      "Interlocking Joint Eliminates Sightlines and Gaps",
      "Chew-Resistant for Livestock & Equestrian Stables",
      "Easily Pressure Washed and Sanitized",
      "100% Weatherproof Exterior Cladding",
    ]),
    published: 1,
  },

  // ================= GARDEN BENCHES =================
  {
    id: "bench-classic-municipal-180",
    name: "Classic Municipal Garden Bench with Backrest (1.8m)",
    category: "garden-bench",
    type: "Park Bench with Backrest",
    description: "Ergonomically contoured 4-seater public garden bench constructed with solid recycled plastic lumber slats mounted on powder-coated structural steel legs.",
    image: "/uploads/products/garden-bench/gardenbench-1770441701366-1_medium.webp",
    price: "Inquire for Municipal & Corporate Rates",
    moq: "5 Benches",
    capacity: "4-Person Seating (450 kg)",
    dispatch: "Ready to Ship in 3-5 Days",
    customization: "Custom memorial plaque engraving, armrests, ground bolt kits",
    technical_blurb: "Manufactured with 40x90mm solid plastic lumber slats that never rot or peel paint. Legs include pre-drilled anchor bolt tabs for anti-theft security.",
    applications: "Municipal Parks, Residential Societies, Waterfront Promenades, Hospital Gardens",
    specifications: JSON.stringify({
      Dimensions: "1800 x 650 x 820 mm (L x W x H)",
      "Seating Capacity": "4 Persons",
      Weight: "52 kg",
      Frame: "Heavy Gauge Powder Coated Mild Steel",
      Slats: "Solid Recycled Plastic Lumber 40x90mm",
      "Anchoring": "Surface Bolt Down Anchoring Included",
    }),
    features: JSON.stringify([
      "Zero Painting, Varnishing, or Sanding Ever Needed",
      "Vandalism and Graffiti Resistant Non-Porous Slats",
      "Weighted Design Prevents Tipping",
      "UV Stabilized Color Will Not Fade in Blistering Heat",
    ]),
    published: 1,
  },
  {
    id: "bench-cast-iron-hybrid-150",
    name: "Heavy-Duty Cast Iron & RPL Heritage Bench (1.5m)",
    category: "garden-bench",
    type: "Heritage Park Bench",
    description: "Traditional ornamental cast-iron scrollwork end frames combined with modern indestructible recycled plastic timber slats. Classic beauty with zero maintenance.",
    image: "/uploads/products/garden-bench/gardenbench-1770441701366-1_medium.webp",
    price: "Inquire for Institutional Pricing",
    moq: "5 Benches",
    capacity: "3-Person Seating (380 kg)",
    dispatch: "5-7 Business Days",
    customization: "Black / Antique Bronze frame finish, custom slat colors",
    technical_blurb: "Heavyweight ductile cast-iron sides provide authentic vintage aesthetics, while recycled plastic slats eliminate the wood rot common to heritage park benches.",
    applications: "Heritage Walking Paths, Luxury Resorts, Botanical Gardens, Golf Clubs, Urban Squares",
    specifications: JSON.stringify({
      Dimensions: "1500 x 600 x 780 mm",
      "Seating Capacity": "3 Persons",
      Weight: "58 kg",
      Frame: "Ductile Cast Iron with Anti-Corrosion Primer",
      Slats: "100% Recycled HDPE Slat Profiles",
      Colors: "Teak Brown / Heritage Green",
    }),
    features: JSON.stringify([
      "Victorian Aesthetic with Modern Synthetic Longevity",
      "Heavyweight Anti-Theft Construction",
      "Resistant to High Humidity, Salt Air, and Monsoons",
      "Termite and Wood-Borer Proof",
    ]),
    published: 1,
  },
  {
    id: "bench-backless-promenade-180",
    name: "Contemporary Backless Garden Bench (1.8m)",
    category: "garden-bench",
    type: "Backless Bench",
    description: "Sleek, dual-direction seating bench designed for busy pedestrian thoroughfares, shopping plazas, school campuses, and transit stations.",
    image: "/uploads/products/garden-bench/gardenbench-1770441701366-1_medium.webp",
    price: "Inquire for Bulk Supply",
    moq: "6 Benches",
    capacity: "4-5 Persons (450 kg)",
    dispatch: "3-5 Business Days",
    customization: "Length variations (1.2m, 1.5m, 1.8m, 2.4m)",
    technical_blurb: "Provides two-way access seating with rounded safety edges. Ideal for middle walkways and garden centerpoints.",
    applications: "Commercial Plazas, School Courtyards, Sports Stadiums, Corporate IT Parks",
    specifications: JSON.stringify({
      Dimensions: "1800 x 480 x 450 mm (L x W x H)",
      "Seating Capacity": "4-5 Persons",
      Weight: "39 kg",
      Slats: "4x Solid Recycled Plastic Lumber Planks",
      Frame: "Heavy Tubular Steel with Zinc Primer",
    }),
    features: JSON.stringify([
      "Dual-Orientation Seating for Open Plazas",
      "Fast Draining Surface Stays Dry After Rains",
      "Rounded Ergonomic Safety Edges",
      "100% Circular Economy Recycled Materials",
    ]),
    published: 1,
  },

  // ================= TABLES =================
  {
    id: "table-rpl-aframe-picnic",
    name: "Recycled Plastic A-Frame Picnic Table (1.8m / 6-8 Seater)",
    category: "plastic-table",
    type: "Picnic Table Set",
    description: "All-in-one picnic table and dual attached benches built entirely from heavy recycled plastic lumber. Extremely heavy and stable, will never blow away or rot.",
    image: "/uploads/products/categories/plastic-table-1770446441648-0_medium.webp",
    price: "Inquire for Institutional Pricing",
    moq: "3 Sets",
    capacity: "6-8 Persons (750 kg Total Load)",
    dispatch: "5-7 Business Days",
    customization: "Parasol umbrella hole (50mm), wheelchair accessible overhang",
    technical_blurb: "Constructed using 38x140mm tabletop planks fastened to massive structural support frames. Total unit weight prevents theft and wind uplift.",
    applications: "School Campuses, Public Park Picnics, Corporate Canteens, Beachside Resorts, Highway Rest Stops",
    specifications: JSON.stringify({
      Dimensions: "1800 x 1550 x 760 mm (L x W x H)",
      "Tabletop Size": "1800 x 750 mm",
      "Seating Capacity": "6-8 Adults",
      Weight: "115 kg (Ultra-Stable)",
      Material: "100% Recycled HDPE Plastic Lumber",
      Colors: "Dual Tone (Teak Tabletop + Black Frame) or Solid Green",
    }),
    features: JSON.stringify([
      "All-Weather Proof: Rain, Intense Sun, Snow, or Marine Air",
      "Food-Safe Easy Wipe Clean Surface",
      "Extremely Heavy (115kg) — Anti-Theft & Tip Proof",
      "No Splinters, No Painting, No Maintenance",
    ]),
    published: 1,
  },
  {
    id: "table-rpl-dining-1208",
    name: "Commercial Outdoor Dining Table (1200x800mm / 4-Seater)",
    category: "plastic-table",
    type: "Outdoor Dining Table",
    description: "Modern rectangular dining table with a recycled plastic lumber slatted top and weather-resistant aluminum/steel legs. Perfect for outdoor cafes and restaurants.",
    image: "/uploads/products/categories/plastic-table-1770446441648-0_medium.webp",
    price: "Inquire for Hospitality Pricing",
    moq: "5 Tables",
    capacity: "4-Person Dining (200 kg)",
    dispatch: "3-5 Business Days",
    customization: "Custom frame height, umbrella center hole",
    technical_blurb: "Slatted recycled lumber top allows rain runoff and resists hot coffee cups, food stains, mustard, and wine spills without staining.",
    applications: "Rooftop Cafes, Outdoor Restaurant Patios, Resort Poolside Dining, Garden Terraces",
    specifications: JSON.stringify({
      Dimensions: "1200 x 800 x 750 mm (L x W x H)",
      "Seating Capacity": "4 Persons",
      Weight: "36 kg",
      Tabletop: "Recycled Plastic Lumber 25x90mm Slats",
      Frame: "Powder Coated Marine-Grade Aluminum / Steel",
    }),
    features: JSON.stringify([
      "Stain Proof: Oils, Wine, and Condiments Wipe Clean",
      "Will Not Rust, Peel, or Crack under Direct Sun",
      "Leveling Glides Included for Uneven Pavements",
      "Commercial Hospitality Grade Durability",
    ]),
    published: 1,
  },
  {
    id: "table-rpl-round-bistro-90",
    name: "Round Recycled Plastic Cafe Bistro Table (900mm Dia)",
    category: "plastic-table",
    type: "Bistro Table",
    description: "Compact circular outdoor table featuring radial recycled plastic lumber planks on a sturdy central pedestal base. Ideal for coffee shops and balcony spaces.",
    image: "/uploads/products/categories/plastic-table-1770446441648-0_medium.webp",
    price: "Inquire for Cafe Package Deals",
    moq: "6 Tables",
    capacity: "3-4 Persons",
    dispatch: "3-5 Business Days",
    customization: "Color combinations, center umbrella grommet",
    technical_blurb: "Radial precision CNC-cut recycled lumber segments mounted to cross-braced steel spider under-frame.",
    applications: "Coffee Shops, Bakery Balconies, Hotel Terraces, Society Clubhouses",
    specifications: JSON.stringify({
      Dimensions: "900 mm Diameter x 750 mm Height",
      "Seating Capacity": "3-4 Persons",
      Weight: "24 kg",
      Base: "Heavy Circular Weighted Steel Base",
      Top: "Recycled Plastic Lumber Radial Slats",
    }),
    features: JSON.stringify([
      "Compact Footprint for Small Patios & Walkways",
      "Weighted Base Resists High Wind Blow-Over",
      "Zero Rot or Water Swelling",
      "Eco-Friendly Sustainable Statement Piece",
    ]),
    published: 1,
  },

  // ================= CUSTOM PRODUCTS & FENCING =================
  {
    id: "custom-industrial-molded-parts",
    name: "Custom Recycled Plastic Industrial Shapes & Parts",
    category: "custom-products",
    type: "Custom Molded Profiles",
    description: "Bespoke industrial plastic components compression-molded and CNC-machined from 100% recycled polymers to your engineering drawings.",
    image: "/uploads/products/categories/categories-1770374476904-61107_medium.webp",
    price: "Custom Quoted from CAD Drawing",
    moq: "Batch Minimums Apply",
    capacity: "Industrial Grade",
    dispatch: "2-3 Weeks Tooling & Sample",
    customization: "Custom molds, machining, tapping, and tolerances",
    technical_blurb: "Engineering-grade recycled HDPE, UHMW-PE, and PP composites formulated for wear resistance, low friction, and chemical endurance.",
    applications: "Conveyor Guides, Chute Liners, Marine Bumpers, Chemical Tank Saddles, Heavy Equipment Bushings",
    specifications: JSON.stringify({
      Material: "Engineered Recycled Polyolefin Alloys",
      Machining: "CNC Milling, Turning, Routing, Drilling",
      Density: "0.95 - 0.98 g/cm³",
      Resistance: "High Chemical, Acid & Alkali Immunity",
    }),
    features: JSON.stringify([
      "Custom Extrusion & Compression Molding Capabilities",
      "Substitutes Expensive Nylon / UHMW Virgin Plastics",
      "High Abrasion Resistance & Low Friction Coefficient",
      "ISO 9001:2015 Certified Manufacturing Tolerances",
    ]),
    published: 1,
  },
  {
    id: "fence-rpl-ranch-rail-3rail",
    name: "Recycled Plastic Post & Rail Ranch Fencing",
    category: "custom-products",
    type: "Agricultural & Perimeter Fencing",
    description: "Indestructible 3-rail post & rail fencing system made entirely from solid recycled plastic lumber. Eliminates painting, rotting, cribbing, and livestock injury.",
    image: "/uploads/products/categories/categories-1770374476904-61107_medium.webp",
    price: "Inquire for Per-Meter Run Rate",
    moq: "50 Running Meters",
    capacity: "Livestock & Boundary Security",
    dispatch: "5-7 Business Days",
    customization: "2-Rail, 3-Rail, or 4-Rail configurations in White, Brown, or Black",
    technical_blurb: "Mortised posts allow thermal floating of horizontal rails without buckling. Non-toxic polymer formulation safe for horses and livestock.",
    applications: "Equine Paddocks, Stud Farms, Solar Power Plant Perimeters, Farmhouse Boundaries, Golf Courses",
    specifications: JSON.stringify({
      "Post Dimensions": "100 x 100 mm (4x4 in) x 2.1m (Direct In-Ground Burial)",
      "Rail Dimensions": "38 x 140 mm (2x6 in) x 3.0m (10ft)",
      Material: "100% Recycled HDPE Plastic Lumber",
      Colors: "Ranch White, Teak Brown, Jet Black",
    }),
    features: JSON.stringify([
      "Never Needs Painting or Creosote Chemical Staining",
      "Horses & Livestock Will Not Chew (Crib-Proof)",
      "Zero Splinters: Safe for Animals and Children",
      "Withstands Soil Moisture & Termite Attack Indefinitely",
    ]),
    published: 1,
  },
];

async function seed() {
  try {
    console.log("Upserting categories...");
    for (const cat of categories) {
      await client.execute({
        sql: `INSERT INTO categories (id, name, slug, description, image, fields)
              VALUES (?, ?, ?, ?, ?, ?)
              ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                slug = excluded.slug,
                description = excluded.description,
                image = excluded.image,
                fields = excluded.fields`,
        args: [cat.id, cat.name, cat.slug, cat.description, cat.image, cat.fields],
      });
    }
    console.log(`✅ Upserted ${categories.length} categories.`);

    console.log("Upserting products...");
    for (const p of products) {
      await client.execute({
        sql: `INSERT INTO products (id, name, category, type, description, image, price, moq, capacity, dispatch, customization, technical_blurb, applications, specifications, features, published)
              VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
              ON CONFLICT(id) DO UPDATE SET
                name = excluded.name,
                category = excluded.category,
                type = excluded.type,
                description = excluded.description,
                image = excluded.image,
                price = excluded.price,
                moq = excluded.moq,
                capacity = excluded.capacity,
                dispatch = excluded.dispatch,
                customization = excluded.customization,
                technical_blurb = excluded.technical_blurb,
                applications = excluded.applications,
                specifications = excluded.specifications,
                features = excluded.features,
                published = excluded.published`,
        args: [
          p.id,
          p.name,
          p.category,
          p.type,
          p.description,
          p.image,
          p.price,
          p.moq,
          p.capacity,
          p.dispatch,
          p.customization,
          p.technical_blurb,
          p.applications,
          p.specifications,
          p.features,
          p.published,
        ],
      });
    }
    console.log(`✅ Upserted ${products.length} products.`);

    const totalProds = await client.execute("SELECT COUNT(*) as count FROM products");
    console.log("Total products now in database:", totalProds.rows[0]?.count ?? totalProds.rows[0]?.[0]);

    const totalCats = await client.execute("SELECT COUNT(*) as count FROM categories");
    console.log("Total categories now in database:", totalCats.rows[0]?.count ?? totalCats.rows[0]?.[0]);
  } catch (err) {
    console.error("❌ Seeding failed:", err);
    process.exit(1);
  }
}

seed();
